# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_cancel_all_orders.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_cancel_all_orders.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1frequest_cancel_all_orders.proto\x12\x03rti\"\x81\x03\n\x16RequestCancelAllOrders\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x10\n\x06\x66\x63m_id\x18\x9d\xb3\t \x01(\t\x12\x0f\n\x05ib_id\x18\x9e\xb3\t \x01(\t\x12\x14\n\naccount_id\x18\x98\xb3\t \x01(\t\x12\x39\n\tuser_type\x18\xb4\xb3\t \x01(\x0e\x32$.rti.RequestCancelAllOrders.UserType\x12\x44\n\x0emanual_or_auto\x18\xd6\xb8\t \x01(\x0e\x32*.rti.RequestCancelAllOrders.OrderPlacement\"&\n\x0eOrderPlacement\x12\n\n\x06MANUAL\x10\x01\x12\x08\n\x04\x41UTO\x10\x02\"Z\n\x08UserType\x12\x13\n\x0fUSER_TYPE_ADMIN\x10\x00\x12\x11\n\rUSER_TYPE_FCM\x10\x01\x12\x10\n\x0cUSER_TYPE_IB\x10\x02\x12\x14\n\x10USER_TYPE_TRADER\x10\x03'
)



_REQUESTCANCELALLORDERS_ORDERPLACEMENT = _descriptor.EnumDescriptor(
  name='OrderPlacement',
  full_name='rti.RequestCancelAllOrders.OrderPlacement',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MANUAL', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTO', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=296,
  serialized_end=334,
)
_sym_db.RegisterEnumDescriptor(_REQUESTCANCELALLORDERS_ORDERPLACEMENT)

_REQUESTCANCELALLORDERS_USERTYPE = _descriptor.EnumDescriptor(
  name='UserType',
  full_name='rti.RequestCancelAllOrders.UserType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='USER_TYPE_ADMIN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USER_TYPE_FCM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USER_TYPE_IB', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USER_TYPE_TRADER', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=336,
  serialized_end=426,
)
_sym_db.RegisterEnumDescriptor(_REQUESTCANCELALLORDERS_USERTYPE)


_REQUESTCANCELALLORDERS = _descriptor.Descriptor(
  name='RequestCancelAllOrders',
  full_name='rti.RequestCancelAllOrders',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.RequestCancelAllOrders.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.RequestCancelAllOrders.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fcm_id', full_name='rti.RequestCancelAllOrders.fcm_id', index=2,
      number=154013, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ib_id', full_name='rti.RequestCancelAllOrders.ib_id', index=3,
      number=154014, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='rti.RequestCancelAllOrders.account_id', index=4,
      number=154008, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_type', full_name='rti.RequestCancelAllOrders.user_type', index=5,
      number=154036, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manual_or_auto', full_name='rti.RequestCancelAllOrders.manual_or_auto', index=6,
      number=154710, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTCANCELALLORDERS_ORDERPLACEMENT,
    _REQUESTCANCELALLORDERS_USERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=426,
)

_REQUESTCANCELALLORDERS.fields_by_name['user_type'].enum_type = _REQUESTCANCELALLORDERS_USERTYPE
_REQUESTCANCELALLORDERS.fields_by_name['manual_or_auto'].enum_type = _REQUESTCANCELALLORDERS_ORDERPLACEMENT
_REQUESTCANCELALLORDERS_ORDERPLACEMENT.containing_type = _REQUESTCANCELALLORDERS
_REQUESTCANCELALLORDERS_USERTYPE.containing_type = _REQUESTCANCELALLORDERS
DESCRIPTOR.message_types_by_name['RequestCancelAllOrders'] = _REQUESTCANCELALLORDERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestCancelAllOrders = _reflection.GeneratedProtocolMessageType('RequestCancelAllOrders', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCANCELALLORDERS,
  '__module__' : 'request_cancel_all_orders_pb2'
  # @@protoc_insertion_point(class_scope:rti.RequestCancelAllOrders)
  })
_sym_db.RegisterMessage(RequestCancelAllOrders)


# @@protoc_insertion_point(module_scope)
